# Generated by Django 2.1.5 on 2019-01-06 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ident', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('comment_count', models.IntegerField()),
                ('scraped', models.DateTimeField(auto_now_add=True)),
                ('published', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ident', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('thread_id', models.CharField(max_length=40)),
                ('parent_id', models.CharField(max_length=40)),
                ('body', models.TextField()),
                ('total_votes', models.IntegerField()),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archival.Article')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('avatar', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('login_provider', models.CharField(max_length=40)),
                ('moderator', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archival.User'),
        ),
    ]
