# Generated by Django 2.1.5 on 2019-01-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ident',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ident',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
