version: '3'
services:
  site:
    restart: always
    build: ./comments
    hostname: site
    command: python comments/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - rabbitmq

  worker:
    restart: always
    build: ./comments
    command: ./run_celery.sh
    volumes:
      - .:/app
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    restart: always
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
